from .classes import *
from .game_engine import State

levels = {
    "original_level_1": State(
        width=19,
        height=11,
        player=Player(11, 8),
        boxes=[Box(x, y) for x, y in [(2, 7), (5, 2), (5, 4), (5, 7), (7, 3), (7, 4)]],
        storages=[
            Storage(x, y)
            for x, y in [(16, 6), (16, 7), (16, 8), (17, 6), (17, 7), (17, 8)]
        ],
        walls=[
            Wall(x, y)
            for x, y in [
                (0, 5),
                (0, 6),
                (0, 7),
                (0, 8),
                (1, 5),
                (1, 8),
                (2, 3),
                (2, 4),
                (2, 5),
                (2, 8),
                (3, 3),
                (3, 8),
                (4, 0),
                (4, 1),
                (4, 2),
                (4, 3),
                (4, 5),
                (4, 6),
                (4, 8),
                (4, 9),
                (4, 10),
                (5, 0),
                (5, 10),
                (6, 0),
                (6, 5),
                (6, 6),
                (6, 8),
                (6, 10),
                (7, 0),
                (7, 5),
                (7, 6),
                (7, 8),
                (7, 10),
                (8, 0),
                (8, 1),
                (8, 2),
                (8, 3),
                (8, 8),
                (8, 10),
                (9, 3),
                (9, 4),
                (9, 5),
                (9, 6),
                (9, 10),
                (10, 6),
                (10, 8),
                (10, 9),
                (10, 10),
                (11, 6),
                (11, 9),
                (12, 6),
                (12, 8),
                (12, 9),
                (13, 5),
                (13, 6),
                (13, 8),
                (13, 9),
                (14, 5),
                (14, 9),
                (15, 5),
                (15, 9),
                (16, 5),
                (16, 9),
                (17, 5),
                (17, 9),
                (18, 5),
                (18, 6),
                (18, 7),
                (18, 8),
                (18, 9),
            ]
        ],
    ),
    "level_with_3_boxes": State(
        width=6,
        height=6,
        player=Player(1, 1),
        boxes=[Box(2, 2), Box(3, 3), Box(2, 4)],
        storages=[Storage(2, 2), Storage(3, 4), Storage(4, 3)],
        walls=[
            Wall(i, j) for i in range(6) for j in range(6) if i in {0, 5} or j in {0, 5}
        ],
    ),
    "hard_human_level": State(
        width=8,
        height=9,
        player=Player(2, 2),
        boxes=[
            Box(3, 2),
            Box(4, 3),
            Box(4, 4),
            Box(1, 6),
            Box(3, 6),
            Box(4, 6),
            Box(5, 6),
        ],
        storages=[
            Storage(1, 2),
            Storage(5, 3),
            Storage(1, 4),
            Storage(4, 5),
            Storage(3, 6),
            Storage(6, 6),
            Storage(4, 7),
        ],
        walls=[
            Wall(x, y)
            for x, y in [
                (2, 0),
                (3, 0),
                (4, 0),
                (5, 0),
                (6, 0),
                (0, 1),
                (1, 1),
                (2, 1),
                (6, 1),
                (0, 2),
                (6, 2),
                (0, 3),
                (1, 3),
                (2, 3),
                (6, 3),
                (0, 4),
                (2, 4),
                (3, 4),
                (6, 4),
                (0, 5),
                (2, 5),
                (6, 5),
                (7, 5),
                (0, 6),
                (7, 6),
                (0, 7),
                (7, 7),
                (0, 8),
                (1, 8),
                (2, 8),
                (3, 8),
                (4, 8),
                (5, 8),
                (6, 8),
                (7, 8),
            ]
        ],
    ),
    "level_easy": State(
        width=8,
        height=8,
        player=Player(1, 1),
        boxes=[Box(2, 3)],
        storages=[Storage(2, 6)],
        walls=[
            Wall(i, j) for i in range(8) for j in range(8) if i in {0, 7} or j in {0, 7}
        ],
    ),
    "level_easiest": State(
        width=6,
        height=6,
        player=Player(1, 1),
        boxes=[Box(2, 2)],
        storages=[Storage(2, 3)],
        walls=[
            Wall(i, j) for i in range(6) for j in range(6) if i in {0, 5} or j in {0, 5}
        ],
    ),
}
